[project]
name = "package-manager-helper"
version = "0.1.0"
description = "Helper project for generating template files"
readme = "README.md"
license = "MIT"
authors = [{ name = "Template Helper" }]
requires-python = ">=3.11"
dependencies = []

[tool.uv]
package = false

[dependency-groups]
# :TODO: Remove pylint when ruff supports all pylint rules
dev = []
